name: cartcell
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=2.1
  - pandas>=2.2
  - matplotlib>=3.9
  - scipy>=1.14
  - ipykernel
  - python-dotenv
  - pip
  - pip:
      - -e ./practical_identifiability
